language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- docker pull mumuki/mumuki-python-worker
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo-deploy/master/travis_deploy
  && chmod u+x travis_deploy
- ./travis_deploy python
